name: Receiver Workflow

on:
  repository_dispatch:
  types: [githubActions-release-published]

permissions: write-all

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Log event payload
        run: echo "Received event payload: ${{ toJson(github.event) }}"