name: Receiver Workflow

on:
  repository_dispatch:
    types: [githubActions-release-published, githubActions_release]

permissions: write-all

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Log event payload
        run: |
          if [ "${{ github.event_name }}" == "githubActions-release-published" ]; then
            VERSION=${{ github.event.client_payload.ort_release_version }}
          else
            VERSION=${{ github.event.client_payload.githubActions.version }}
          fi
          echo "Received event payload: ${VERSION}"